security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: user, roles: [ 'ROLE_USER' ] }
                    admin: { password: admin, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/event/admin/login$
            security: false

        admin:
            pattern:   ^/event/admin/
            anonymous: true
            form_login:
                login_path: /event/admin/login
                check_path: /event/admin/login_check
                default_target_path: /event/admin/
            logout:
                path:    /event/admin/logout
                target:  /event/admin/login
            switch_user: { role: ROLE_ADMIN }

    access_control:
        # Backend
        - { path: ^/event/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/event/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/event/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/event/admin/, role: ROLE_ADMIN }
